#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pytest-cov
Version  : 2.12.1
Release  : 67
URL      : https://files.pythonhosted.org/packages/63/3a/747e953051fd6eb5fb297907a825aad43d94c556d3b9938fc21f3172879f/pytest-cov-2.12.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/63/3a/747e953051fd6eb5fb297907a825aad43d94c556d3b9938fc21f3172879f/pytest-cov-2.12.1.tar.gz
Summary  : Pytest plugin for measuring coverage.
Group    : Development/Tools
License  : MIT
Requires: pytest-cov-license = %{version}-%{release}
Requires: pytest-cov-python = %{version}-%{release}
Requires: pytest-cov-python3 = %{version}-%{release}
Requires: coverage
Requires: pip
Requires: pytest
Requires: setuptools
Requires: six
Requires: toml
Requires: virtualenv
BuildRequires : Sphinx
BuildRequires : Sphinx-python
BuildRequires : buildreq-distutils3
BuildRequires : coverage
BuildRequires : coverage-python
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : setuptools
BuildRequires : six
BuildRequires : toml
BuildRequires : tox
BuildRequires : virtualenv

%description
Overview
        ========
        
        .. start-badges

%package license
Summary: license components for the pytest-cov package.
Group: Default

%description license
license components for the pytest-cov package.


%package python
Summary: python components for the pytest-cov package.
Group: Default
Requires: pytest-cov-python3 = %{version}-%{release}

%description python
python components for the pytest-cov package.


%package python3
Summary: python3 components for the pytest-cov package.
Group: Default
Requires: python3-core
Provides: pypi(pytest_cov)
Requires: pypi(coverage)
Requires: pypi(pytest)
Requires: pypi(toml)

%description python3
python3 components for the pytest-cov package.


%prep
%setup -q -n pytest-cov-2.12.1
cd %{_builddir}/pytest-cov-2.12.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1622579096
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pytest-cov
cp %{_builddir}/pytest-cov-2.12.1/LICENSE %{buildroot}/usr/share/package-licenses/pytest-cov/07800edab5f4e77a7371e226f11ba91f963a11cf
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pytest-cov/07800edab5f4e77a7371e226f11ba91f963a11cf

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
